# Generated by Django 4.1.2 on 2022-11-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("albums", "0001_initial"),
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artists.artist"
            ),
        ),
    ]
