# Generated by Django 4.1.2 on 2022-10-19 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_alter_album_creation_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="creation_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 19, 15, 21, 54, 469506, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
