# Generated by Django 4.1.2 on 2022-10-20 03:30

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0005_alter_album_creation_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="creation_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 20, 3, 30, 22, 977055, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
