# Generated by Django 4.1.2 on 2022-10-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0006_album_created_album_modified_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="album", name="creation_datetime",),
    ]
